project_id = "kbcqvqfnavkagdngapff"

[functions.extract-pdf]
verify_jwt = false

[functions.publish-due-posts]
verify_jwt = false

[functions.linkedin-oauth-start]
verify_jwt = false

[functions.linkedin-oauth-callback]
verify_jwt = false

[functions.ai-extract]
verify_jwt = false
